# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wander' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  # Pods for Wander
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end
